from .factory import NODE_CLASS_MAPPINGS as _FACTORY_NODES, NODE_DISPLAY_NAME_MAPPINGS as _FACTORY_NAMES
from .loop import NODE_CLASS_MAPPINGS as _LOOP_NODES, NODE_DISPLAY_NAME_MAPPINGS as _LOOP_NAMES
from .scale import NODE_CLASS_MAPPINGS as _SCALE_NODES, NODE_DISPLAY_NAME_MAPPINGS as _SCALE_NAMES

NODE_CLASS_MAPPINGS = {**_FACTORY_NODES, **_LOOP_NODES, **_SCALE_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_FACTORY_NAMES, **_LOOP_NAMES, **_SCALE_NAMES}
